# This file was generated by GoReleaser. DO NOT EDIT.
cask "umbraco-cli" do
  version "0.4.23"

  on_macos do
    on_arm do
      sha256 "f3cb0f26ab5039848d7e8ee5728431576de3f8706778e5872972489dbcbf390d"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "df9b81d4b6ea09c72d43898751426208c6c0a16e6c06a159d43824384278cdb7"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e1101c3e10471ca876424ae1c0363fec97b8933422a3531acad1804e20fe7c8f"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "003bba870ae888bad2e590335fa70282929f69d8f5341ee5d5bae8c97205fb11"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "umbraco-cli"
  desc "Command-line client for the Umbraco Management API"
  homepage "https://github.com/albanistrefi/umbraco_CLI"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "umbraco"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/umbraco"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The `umbraco` binary expects these environment variables:
      UMBRACO_BASE_URL
      UMBRACO_CLIENT_ID
      UMBRACO_CLIENT_SECRET

    The release archives are not notarized yet, so the cask clears the macOS
    quarantine attribute during installation.
  EOS
end
