# This file was generated by GoReleaser. DO NOT EDIT.
cask "umbraco-cli" do
  name "umbraco-cli"
  desc "Command-line client for the Umbraco Management API"
  homepage "https://github.com/albanist/umbraco_CLI"
  version "0.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "umbraco"

  on_macos do
    on_intel do
      url "https://github.com/albanist/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_macOS_x86_64.tar.gz"
      sha256 "09589d4befa0487e69924b47c24447e80b86f318610d93abe159106a6edfd552"
    end
    on_arm do
      url "https://github.com/albanist/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_macOS_arm64.tar.gz"
      sha256 "2d77b22d54a3287805f155b2fb10efbf34def8b1a5bee1f78aef6a9ee8a358dc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/albanist/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_Linux_x86_64.tar.gz"
      sha256 "589fa1b6d27ba158c0ed5d0b7d7aced64ffba6387bb2761428f4d83d7a151375"
    end
    on_arm do
      url "https://github.com/albanist/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_Linux_arm64.tar.gz"
      sha256 "ab97f6ebdc03867556d3e6e7198fe2f2e0e98a03e42a1a9f0a100eeaefd39e62"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/umbraco"]
    end
  end

  caveats do
    "The `umbraco` binary expects these environment variables:"
    "  UMBRACO_BASE_URL"
    "  UMBRACO_CLIENT_ID"
    "  UMBRACO_CLIENT_SECRET"
    ""
    "The release archives are not notarized yet, so the cask clears the macOS"
    "quarantine attribute during installation."
  end

  # No zap stanza required
end
