# This file was generated by GoReleaser. DO NOT EDIT.
cask "umbraco-cli" do
  version "0.4.21"

  on_macos do
    on_arm do
      sha256 "c0726e1753a64b328cc8e01341443fb9a0a3767dcd1a7248b5a2032ededbc560"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "0ff0e04a252d57b8d23889231c028f91be6a14170f4f88dc5706f9522da1d039"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c0e473d6b39b615aa090775460a3bdd8563b0743becb6120461076b135243a10"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "27b75400291a89dd61ad0c437c7759299f99930799d842a662643776dfbd4edb"
      url "https://github.com/albanistrefi/umbraco_CLI/releases/download/v#{version}/umbraco-cli_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "umbraco-cli"
  desc "Command-line client for the Umbraco Management API"
  homepage "https://github.com/albanistrefi/umbraco_CLI"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "umbraco"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/umbraco"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The `umbraco` binary expects these environment variables:
      UMBRACO_BASE_URL
      UMBRACO_CLIENT_ID
      UMBRACO_CLIENT_SECRET

    The release archives are not notarized yet, so the cask clears the macOS
    quarantine attribute during installation.
  EOS
end
